### ISSUE TITLE
Cant load World

### ISSUE THREAD

**Issue by KeganATSMC** [Wardenfar/Osm2Map#4]
Hello, I started a spigot server (fully functional) and the plugin is not working i am stuck on the step where it says Configure Bukkit. the setup is very confusing and cant get anywhere past that point

**Comment by Wardenfar** [comment]
Hello
In the step "configure bukkit" you have to add this snippet of code at the end of bukkit.yml ( to replace the world generator )

**Comment by KeganATSMC** [comment]
i added the code and it is still not working here is the bukkit.yml in the form of a txt file
[bukkit.txt](https://github.com/Wardenfar/Osm2Map/files/7953929/bukkit.txt)
t.yml

**Comment by Wardenfar** [comment]
When you say : "it is not working"
Can you give me some context : logs, what is working and what is not ?

**Comment by KeganATSMC** [comment]
[latest.log](https://github.com/Wardenfar/Osm2Map/files/7954053/latest.log)
here is the latest log also when i gave you the bukkit file i was intending for you to take a look at it and see if i needed to change anything.

**Comment by Wardenfar** [comment]
The file bukkit.yml seems ok
but the logs says that you miss the step : Requirements (FAWE)
https://github.com/Wardenfar/Osm2Map/blob/master/.github/doc/INSTALL.md#requirements-fawe

you need to do all the steps in this INSTALL wiki page

**Comment by KeganATSMC** [comment]
![image](https://user-images.githubusercontent.com/68925646/151456180-71c8af01-bb5e-4ccf-af3c-547570ed131d.png)
that's weird i have it installed already is there a certain version i have to install

**Comment by Wardenfar** [comment]
Select spigot 1.12.2 in the version select.
![image](https://user-images.githubusercontent.com/20862992/151457681-af382648-bd65-46cd-86ff-be902169adb4.png)
It is the first button, not the second "Voxel Snipper"
![image](https://user-images.githubusercontent.com/20862992/151457488-ea04efc3-f682-4a0c-9c6f-c6e5e19bf73e.png)

**Comment by KeganATSMC** [comment]
[latest.log](https://github.com/Wardenfar/Osm2Map/files/7954604/latest.log)
now it is giving me this message

**Comment by KeganATSMC** [comment]
update i almost got it to work but then when i thought everything was going smooth i got thi
[latest.log](https://github.com/Wardenfar/Osm2Map/files/795
[crash-2022-01-27_18.11.58-server.txt](https://github.com/Wardenfar/Osm2Map/files/7954676/crash-2022-01-27_18.11.58-server.txt)
4675/latest.log)
s

**Comment by Wardenfar** [comment]
You need to disable this : 

tile": { .... "active": true,

In plugins/osm2map/config/config.json

**Comment by KeganATSMC** [comment]
the world loaded but it is nothing but void

**Comment by KeganATSMC** [comment]
update now i have this flat patch of grass no roads or nothing is there a command i have to run

**Comment by KeganATSMC** [comment]
Never mind it worked thanks for all your help i will open a new thread or look back on this thread if any more problems arise


Thanks
